name 'chef-respy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-respy'
long_description 'Installs/Configures chef-respy'
version '0.1.0'
